헤더 컴포넌트 제작
UnivChat/web-client pull request #13
Opened 2023-04-06 14:39 UTC by Duck-98

# Describe your changes
- 헤더 퍼블리싱을 했습니다.
- 뒤로가기 SVG를 추가했습니다.
#### 사용방법
1. 뒤로가기 버튼을 사용할 때
`<Header title={title} hasBackButton />
`
2. 타이틀만 필요할 때
`<Header title={title} />
`

## Issue ticket number and link (optional)

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
svg 아이콘 width는 xd디자인이랑 똑같이 맞추면 좀 다르게 나오는데 어떻게 해결하는게 좋을까요?
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-04-06 16:38 UTC, minsoo-web requested changes
리뷰 남깁니다~!

2023-04-15 14:44 UTC, minsoo-web requested changes
리뷰 남깁니다~!

2023-04-18 13:57 UTC, minsoo-web requested changes
리뷰 다시 드립니다~!

2023-04-23 08:10 UTC, minsoo-web requested changes

2023-04-29 12:50 UTC, Duck-98 commented on src/components/Common/UI/Header/BackButton.tsx
> +    <Styled.Button type="button" onClick={handleBackClick}>
이렇게 쓸 수 있는지 처음 알았네요,,,
수정했습니다

2023-04-29 12:51 UTC, Duck-98 commented on src/components/Common/UI/Header/Header.styles.ts
> +`;
엇 이거 저번에 삭제 했는데 적용이 안됐나보네요 ㅠㅠ 수정했습니다

2023-05-06 04:44 UTC, minsoo-web approved these changes

2023-05-06 04:45 UTC, merged