Feat home amanity
UnivChat/web-client pull request #18
Opened 2023-04-16 11:15 UTC by tlshoon

# Describe your changes
메인 화면 편의시설 컴포넌트 퍼블리싱 했습니다.
amanity로 이름 지어서 작업했습니다.

## Issue ticket number and link (optional)
작업을 미리 해둬서 리뷰 받고 문제 없으면 은진님이 #15 에서 이어서 하시면 될 것 같습니다!

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-04-18 14:02 UTC, minsoo-web requested changes
리뷰 남깁니다~!

2023-04-23 08:44 UTC, minsoo-web requested changes
리뷰 드립니다!

2023-05-06 05:02 UTC, minsoo-web reviewed
리뷰 더 남깁니다! page.tsx 는 이 폴더에 불필요해보이는데 맞나요?!

2023-05-06 05:02 UTC, minsoo-web commented on src/components/Home/Amenity/Amenity.style.ts
> +}
flex의 기본 값을 함수의 파라미터로 넣어주는 것을 추천드립니다.

추가로 이 함수는 프로젝트 전역에서 사용될 유틸함수이기 때문에 styles 폴더에 정의해주세요
파일 이름 예시: 
src > styles > utils > flex.ts
src > styles > utils.ts

2023-05-06 05:02 UTC, minsoo-web commented on src/components/Home/Amenity/Amenity.style.ts
> +}
![Uploading image.png…]()

2023-05-06 05:02 UTC, minsoo-web commented on src/components/Home/Amenity/Amenity.style.ts
> +}
<img width="578" alt="image" src="https://user-images.githubusercontent.com/57122180/236600941-f3778587-bbc0-4367-81ba-f7c679b93661.png">

2023-05-06 12:23 UTC, tlshoon commented on src/components/Home/Amenity/Amenity.style.ts
> +}
오!! 감사합니다!! 이렇게 하니까 스타일 적용할 때 훨씬 명확하고 좋네요!!

2023-05-06 12:23 UTC, tlshoon commented on src/components/Home/Amenity/Amenity.style.ts
> +}
네! 알겠습니다

2023-05-06 12:47 UTC, tlshoon commented
수정 사항
1) index.page.tsx  => Amenity.tsx 파일명 수정
2) flex 함수 styles 폴더에 정의
3) eslint 적용

2023-05-15 18:14 UTC, minsoo-web approved these changes
고생하셨습니다! 머지하겠습니다

2023-05-15 18:14 UTC, merged