#17 채팅 메인 페이지 퍼블리싱
UnivChat/web-client pull request #20
Opened 2023-04-18 13:58 UTC by Duck-98

# Describe your changes
- 채팅 메인 페이지 퍼블리싱입니다.
<img width="290" alt="image" src="https://user-images.githubusercontent.com/72850354/232799649-b16d1063-a00c-4fa2-8aed-ecd269af0636.png">

## Issue ticket number and link (optional)
#17 채팅 메인페이지 퍼블리싱
## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
상단 채팅 레이아웃은 아직 적용하지않았는데 해야하나요?
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-04-23 08:21 UTC, minsoo-web requested changes
리뷰 드립니당

2023-04-29 12:55 UTC, Duck-98 commented on src/pages/chat/chatPage.styles.ts
구글링하다가 vh로 하신 분이 있어서 저도 써봤는데 잘 안쓰나보네요ㅠㅠ px로 다시 수정했습니다!

2023-04-29 12:56 UTC, Duck-98 commented on src/pages/chat/chatPage.styles.ts
> +};
확인했습니다! 감사합니다

2023-04-29 12:56 UTC, Duck-98 commented on src/pages/chat/chatPage.styles.ts
수정했습니다!

2023-04-29 12:56 UTC, Duck-98 commented on src/pages/chat.page.tsx
삭제했습니다!

2023-04-29 12:56 UTC, Duck-98 commented on src/assets/svgs/dormitory-chat.svg
수정했습니다!

2023-05-15 18:16 UTC, minsoo-web requested changes
덕경님 충돌 해결해주시고, px을 사용하는 것이 아닌, pxToRem 유틸함수를 사용해주세요,
그리고 HomeAmenity 쪽에 flex 함수를 활용한 스타일 코드들이 있으니 참고해서 수정 부탁드립니다.

2023-05-16 08:20 UTC, Duck-98 commented
> 덕경님 충돌 해결해주시고, px을 사용하는 것이 아닌, pxToRem 유틸함수를 사용해주세요, 그리고 HomeAmenity 쪽에 flex 함수를 활용한 스타일 코드들이 있으니 참고해서 수정 부탁드립니다.

수정사항 반영했습니다!

2023-05-19 17:43 UTC, minsoo-web requested changes
리뷰 드립니다!

2023-05-19 17:43 UTC, minsoo-web commented on src/pages/chat/chat.styles.ts
> +  height: 188px;
이친구 pxToRem 적용시켜주세요
그리고 자주 사용되는 box-shadow 상수로 정리해두면 더 좋을 것 같습니다

2023-05-22 09:04 UTC, Duck-98 commented on src/pages/chat/chat.styles.ts
> +  height: 188px;
확인했습니다!

2023-05-26 07:05 UTC, minsoo-web approved these changes

2023-05-26 07:05 UTC, merged