#14 회원가입, 이메일 인증, 비밀번호 찾기 퍼블리싱
UnivChat/web-client pull request #22
Opened 2023-04-23 16:34 UTC by tlshoon

# Describe your changes
회원가입, 이메일 인증 페이지 퍼블리싱 했습니다.

## Issue ticket number and link (optional)
#14 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
비밀번호 찾기 부분과 공통 컴포넌트가 많아서 이어서 작업하겠습니다.

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
storybook 개발 경험이 없어서 맞게 사용하였는지 확인 받고 싶습니다!!
- 🔥 이건 꼭 확인해주세요!

2023-05-15 18:47 UTC, minsoo-web requested changes
1차 리뷰로 나눠서 리뷰 남기겠습니다!

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.stories.tsx
우선 컴포넌트 폴더 이름은 파스칼 케이스로 지어주세요!
파일 이름도 마찬가지입니다. 
파일 및 폴더 이름만 변경했을 때 git이 제대로 변경사항을 인식하지 못하는 이슈가 있을텐데 구글링을 통해 해결해보시구 잘 안 되면 노티 부탁드립니다

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
> +}
기존에 만든 flex 함수를 쓰면 되지 않나요?

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
> +}
param을 순서에 맞게 넣어야 하는 것은 가독성에 좋지 못한 방법입니다. 개선한 flex 함수를 적용해봅시다!

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
> +  outline: none;
reset.css에 정의 되어 있을겁니다.
없다면 추가해주세요
cursor: pointer는 button이면 default 입니다.
default 속성을 명시하지 않는 걸 습관들이세요!

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
> +  margin-bottom: ${pxToRem(20)};
top과 bottom은 한 줄에 적는 게 가독성에 좋을 때도 있습니다.

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.tsx
> +};
기존에 작업했던 내용이 있지 않나요? 재활용 할 수 있게 개선해보세요!

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.tsx
> +const BodyTop = ({ step }: { step: number }) => (
step보다는 currentStep이 더 맞는 변수명 같은데 제가 이해한 게 맞을까요?

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.tsx
> +const BodyTop = ({ step }: { step: number }) => (
또한 특정 컴포넌트에 종속된 컴포넌트라고 해서 따로 파일로 구분하지 않을 필요는 없습니다. 
Auth.BodyTop.tsx 와 같이 같은 폴더에 정리하면 선언적으로 관심사를 분리할 수 있습니다. 

/Auth
  Auth.tsx
  Auth.composition.tsx
  Auth.styles.ts
  Auth.types.ts
  index.ts

와 같이요!

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.tsx
> +}) => {
타입 선언은 types.ts에 몰아서 정리하는 게 좋습니다.
타입은 참고하는 용도이기 때문에 tsx 파일에 기재해두면 가독성을 해치는 영향을 주더라구요
또한 기재한 타입들은 모두 기본 attribute이기 때문에 이를 활용하면 더 좋을 것 같습니다.
```suggestion

const Foo = (inputProps: InputHTMLAttributes<HTMLInputElement>) => {
  return <input {...inputProps} />
}
```

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
> +export const Input = styled.input<{ width?: string }>`
여기 지정한 타입과 실제로 tsx에서 사용하는 타입이 달라질 경우를 생각해보세요
타입을 두 번 고쳐야 하지 않나요?
types.ts에 한 번에 정의하고 import를 사용한다면 이러한 일이 적어질 겁니다

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
> +  line-height: 1;
팔요한 코드인가요?

2023-05-15 18:47 UTC, minsoo-web commented on src/components/Common/auth/auth.styles.ts
style을 역할에 맞게 묶으면 가독성이 미칩니다. 

저는 개인적으로 다음과 같은 순서에 맞게 적습니다.

1. position
2. width, heigh, padding, margin (박스 요소)
3. color, text, bg, border
4. etc

순서대로 적고 style 코드에 개행을 더하면 가독성에 지대한 영향을 주니, 한 번 적용해보세요

as-is
```ts
background-color: ${colors.grayf8};
  margin-top: ${pxToRem(18)};
  border-top-right-radius: ${pxToRem(40)};
  width: 100vw;
  height: 100vh;
  box-shadow: inset 0 ${pxToRem(4)} ${pxToRem(24)} #00000019;
```

to-be
```ts
  width: 100vw;
  height: 100vh;

  margin-top: ${pxToRem(18)};

  background-color: ${colors.grayf8};
  box-shadow: inset 0 ${pxToRem(4)} ${pxToRem(24)} #00000019;

  border-top-right-radius: ${pxToRem(40)};
```

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/emailauth/emailAuth.hooks.ts
> +export const useEmailAuth = (): UseEmailAuthReturnValue => {
좋은 습관이네요! 좋습니다 ㅎㅎ

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/emailauth/emailAuth.type.ts
> +  handleEmailAuthButtonClick: () => void;
typescript에서 제공하는 타입 중에 VoidFunction 이라는 타입이 있습니다. 
import 할 필요도 없고 자동완성도 되어서 편리합니다.

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/emailauth/index.page.tsx
> +  CommonComponents;
위에서 언급한 리뷰를 적용하면

```ts
import * as Auth from "~/components/Common/Auth"

...

return {
  <Auth.Container>
      <Auth.Text>asd</Auth.Text>
  </Auth.Container>
}
```
와 같이 적을 수 있어 편리할 겁니다!

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/emailauth/index.page.tsx
> +              <CustomInput type="text" name="emailAuth" required />
type="text" 는 default 입니다. 굳이 명시할 필요가 없습니다.

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/emailauth/index.page.tsx
> +          style={{ backgroundColor: emailAuthButtonBgColor }}
style을 props로 받을 거면 styled-components를 쓰는 의미가 퇴색됩니다.
bgColor만 props로 받을 수 있게 하는 건 어떨까요

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/emailauth/index.page.tsx
> +              <CustomInput type="text" name="emailAuth" required />
type: string 이여서 넣어준거라면 옵셔널로 바꿔보세요 어차피 input의 atrribute를 쓰라고 제가 위에서 리뷰 드려서 기본 값으로 들어갑니다.

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/signin/signinPage.type.ts
signin -> signIn 이 맞을 것 같습니다.
혹은 nextjs에서 폴더명은 path니까 sign-in 도 되겠네요

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/signin/signinPage.type.ts
> +  handleSubmit: (e: FormEvent<HTMLFormElement>) => void;
FormEventHandler 라는 게 있을겁니다.

2023-05-15 18:47 UTC, minsoo-web commented on src/pages/auth/signin/signinPage.type.ts
> +  handleIdCheck: (e: MouseEvent<HTMLButtonElement>) => void;
MouseEventHandler 라는 게 있습니다

2023-05-20 05:07 UTC, tlshoon commented on src/components/Common/auth/auth.styles.ts
> +  outline: none;
넵!! 정의되어있어서 삭제했습니다!

2023-05-20 05:12 UTC, tlshoon commented on src/components/Common/auth/auth.tsx
> +};
점을 공통으로 쓰는 부분이 있어서 기존 작업했던 것을 [src/components/Common/auth/auth.tsx]에 넣어놓고 페이지에서         <BodyTopsDots />이렇게 사용하고 있습니다! 혹시 수정해야할까요?

2023-05-20 05:24 UTC, tlshoon commented on src/components/Common/auth/auth.styles.ts
> +  line-height: 1;
삭제했습니다!

2023-05-20 06:01 UTC, tlshoon commented on src/pages/auth/emailauth/index.page.tsx
> +  CommonComponents;
감사합니다! 훨씬 좋은 거 같습니다!

2023-05-20 06:17 UTC, tlshoon commented on src/pages/auth/emailauth/index.page.tsx
> +          style={{ backgroundColor: emailAuthButtonBgColor }}
넵 감사합니다!! style 사용하는 거 지양하도록 하겠습니다!

2023-05-20 06:31 UTC, tlshoon commented on src/components/Common/auth/auth.tsx
> +}) => {
감사합니다! 훨씬 깔끔하고 가독성이 좋습니다

2023-05-20 07:11 UTC, tlshoon commented on src/pages/auth/emailauth/emailAuth.type.ts
> +  handleEmailAuthButtonClick: () => void;
오!! 좋습니다👍🏻

2023-05-20 07:29 UTC, tlshoon commented
코드 리뷰 참고해서 다서 PR 올렸습니다!!

2023-05-26 07:09 UTC, minsoo-web approved these changes
고생하셨습니다 재훈님!

2023-05-26 07:09 UTC, merged