오늘의 식단 페이지
UnivChat/web-client pull request #25
Opened 2023-04-28 04:33 UTC by minjun232

# Describe your changes
오늘의 식단 페이지 작업했습니다.
상단바와 하단바는 아직 넣지 못했습니다.

## Issue ticket number and link (optional)
#16 

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
#16 연락망 페이지

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-04-28 16:17 UTC, tlshoon commented
리뷰 남깁니다!

2023-05-09 19:08 UTC, tlshoon commented on src/pages/home/todaymeal/index.page.tsx
> +import { useRouter } from "next/router";
불필요한 코드입니다.

2023-05-09 19:08 UTC, tlshoon commented on src/pages/home/todaymeal/index.page.tsx
> +      </Styled.MenuContainer>
컴포넌트 단위로 작업하면 좋을 것 같습니다. 중복이 많아서 가독성이 떨어집니다. ```<MenuContainer />```를 밑에도 사용하니 공통 컴포넌트 파일을 따로 만들어서 ```<MenuContainer title="부온프란조" titlePlace="학생미래인재관 2층" color="rgba(0, 49, 151, 0.11)" menuItems={menuItems} />``` 이런식으로 Props로 내려주면 좋을 것 같다고 생각합니

2023-05-09 19:08 UTC, tlshoon commented on src/pages/home/todaymeal/index.page.tsx
> +            </Styled.MenuList>
MenuEach를 여러번 쓰는 것 보다 데이터를 가져와서 식단을 넣는다고 하면  .map을 사용하면 좋을 것 같습니다
```
<>
      {menuItems.map((menuList, index) => (
        <Styled.MenuList key={index}>
          {menuList.map((menuItem, index) => (
            <Styled.MenuEach key={index}>{menuItem}</Styled.MenuEach>
          ))}
        </Styled.MenuList>
      ))}
</>
```

2023-05-15 18:22 UTC, minsoo-web requested changes
리뷰 드립니다!

2023-05-15 18:22 UTC, minsoo-web commented on .editorconfig
불필요한 파일로 보이는데 필요한가요?

2023-05-15 18:22 UTC, minsoo-web commented on package-lock.json
저희는 패키지 관리로 yarn을 사용합니다. 
node_modules, package-lock.json 삭제후 yarn install 진행해주세요

2023-05-15 18:22 UTC, minsoo-web commented on src/pages/home/todaymeal/index.page.tsx
> +import { MenuContainer } from "./todaymeal";
컴포넌트 폴더 이름은 파스칼 케이스로 지어주세요

e.g
camelCase
PascalCase
cebab-case

2023-05-15 18:22 UTC, minsoo-web commented on src/pages/home/todaymeal/todaymeal.styles.ts
> +  align-items: center;
flex 함수를 재훈님이 만든 게 있습니다. 활용해주세요

2023-05-15 18:22 UTC, minsoo-web commented on src/pages/home/todaymeal/todaymeal.styles.ts
> +  align-self: flex-start;
마찬가지로 재훈님 코드를 활용해주세요 다른 리뷰 더 안 남길테니 flex 하드코딩으로 넣은 내용들 수정 같이 부탁드립니다

2023-05-15 18:22 UTC, minsoo-web commented on src/pages/home/todaymeal/todaymeal.tsx
> +export const MenuContainer = ({ ...containerProps }: MenuProps) => {
```suggestion
export const MenuContainer = (containerProps: MenuProps) => {
```
또는

```suggestion
export const MenuContainer = ({ title, titlePlace, color }: MenuProps) => {
```
와 같이 사용해주세요.
불필요한 destructuring 입니다.

2023-05-15 18:22 UTC, minsoo-web commented on src/pages/home/todaymeal/todaymeal.types.tsx
> +  mItems: Array<Array<string>>;
string[][] 가 더 보기 편하지 않나요?!

2023-05-26 07:11 UTC, minsoo-web requested changes
리뷰 다시 드립니다!

2023-05-26 07:11 UTC, minsoo-web commented on package.json
불필요한 변경사항입니다. 패키지 삭제해주시고 버전은 원복해주세요

2023-05-26 07:11 UTC, minsoo-web commented on src/pages/home/todaymeal/todaymeal.styles.ts
> +  align-items: center;
함수 적용을 했으니 위 코드는 삭제해주세요!

2023-05-26 07:11 UTC, minsoo-web commented on src/pages/home/todaymeal/todaymeal.styles.ts
> +  align-self: flex-start;
위 내용 적용이 안 된 것 같습니다 ㅎㅎㅠ

2023-05-28 09:41 UTC, minsoo-web approved these changes

2023-05-28 09:42 UTC, merged