클래스 채팅, 클래스 찾기 페이지 퍼블리싱
UnivChat/web-client pull request #27
Opened 2023-05-03 08:41 UTC by Duck-98

# Describe your changes

### 클래스 채팅 목록 페이지
<img width="294" alt="image" src="https://user-images.githubusercontent.com/72850354/235868623-a5131f76-70b5-44f8-9fd5-75708fea5b28.png">

### 클래스 찾기 페이지
<img width="291" alt="image" src="https://user-images.githubusercontent.com/72850354/235868721-6459704e-4e08-4fbf-91d6-e2d61750a77d.png">

## Issue ticket number and link (optional)

#24 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
-  아직 채팅 메인페이지가 머지되지않아서 머지된다면 추후에 연결해야합니다.

## Questions

- 💬 질문 사항이에요!
페이지 폴더 내에 컴포넌트들을 몰아 놔서 헷갈리는데, 
파일 구조를 어떻게 개선시키는게 좋을지 궁금합니다.
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-05-07 13:45 UTC, tlshoon commented
궁금한 점이 있어서 남깁니다!

2023-05-09 13:18 UTC, Duck-98 commented
> 궁금한 점이 있어서 남깁니다!

@tlshoon  앗 댓글을 지금 봤네요 ㅠㅠ 궁금한게 어떤건가요?

2023-05-09 19:09 UTC, tlshoon commented on src/pages/class/index.page.tsx
> +};
탭바가 들어가는 모든 부분에 NextPageWithLayout과 .layoutConfig = {
  case: "tab"
};를 써야할까요?? 하위 폴더에서 모두 써야하는지 궁금합니다ㅠㅠ

2023-05-09 19:09 UTC, tlshoon commented on src/pages/chat/class/class.styles.ts
> +  flex-direction: column;
flex 자주 사용하여 함수로 만들어 utils폴더에 올렸습니다! dev브랜치에 머지 되면 사용하시면 더 편할 것 같습니다!!

2023-05-09 19:09 UTC, tlshoon commented on src/pages/chat/class/class.styles.ts
> +  height: 20px;
${pxToRem()}을 사용하지 않은 이유가 있나요!?

2023-05-16 08:41 UTC, Duck-98 commented on src/pages/chat/class/class.styles.ts
> +  height: 20px;
방금 수정해서 적용했습니다!

2023-05-16 08:42 UTC, Duck-98 commented on src/pages/chat/class/class.styles.ts
> +  flex-direction: column;
수정해서 적용했습니다!

2023-05-16 08:44 UTC, Duck-98 commented on src/pages/class/index.page.tsx
> +};
늦게 답변드려서 죄송합니다ㅠㅠ 탭바 사용하려면 하단에 layConfig 코드를 사용해야하는거로 알고 있습니다!

2023-05-19 17:56 UTC, minsoo-web requested changes
리뷰 드립니다!

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/ClassChatBox.tsx
> +export default ClassChatBox;
네임드 export 사용하고 있습니다 수정 부탁드립니다!

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/ClassBox.tsx
> +}
props 정리는 ClassBox.types.ts 에 따로 정의해주세요 컨벤션입니다

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/Search.styles.ts
> +  border: none;
reset.css에 정의 되어있을겁니다 없다면 추가해주세요

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/classSearch.styles.ts
> +const sharedTextStyles = css`
자주 반복되어 사용되는데, 공통 스크립트로 만들어서 사용해보면 어떨까여?

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/classbox.styles.ts
> +  display: flex;
불필요해보입니다

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/classbox.styles.ts
> +  height: 85px;
반응형으로 작업해주세요

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/classbox.styles.ts
> +  padding: 0 ${pxToRem(12)} 0 ${pxToRem(12)};
```suggestion
  padding: 0 ${pxToRem(12)};
```
으로 적을 수 있습니다.
불필요하게 가독성이 떨어지는 작성 방법 같습니다 ㅠ

2023-05-19 17:56 UTC, minsoo-web commented on src/pages/chat/class/classSearch/index.page.tsx
> +export default ClassSearch;
namedExport로 수정해주세요

2023-05-26 07:15 UTC, minsoo-web requested changes
충돌만 해결해주세요! 고생 많으셨습니다!

2023-05-26 12:04 UTC, Duck-98 commented
> 충돌만 해결해주세요! 고생 많으셨습니다!

해결했습니다!

2023-05-28 09:50 UTC, minsoo-web approved these changes

2023-05-28 09:51 UTC, merged