#23 마이페이지, 알림 설정 퍼블리싱
UnivChat/web-client pull request #28
Opened 2023-05-05 05:26 UTC by tlshoon

# Describe your changes
<img width="189" alt="스크린샷 2023-05-05 오후 2 22 32" src="https://user-images.githubusercontent.com/87574833/236382860-7b42c874-5e77-49dc-803c-0c9f54c87bb0.png">  <img width="189" alt="스크린샷 2023-05-05 오후 2 22 41" src="https://user-images.githubusercontent.com/87574833/236382866-b44c11f1-0dcb-4ba8-a016-3159878c1f43.png">

## Issue ticket number and link (optional)
#23 마이페이지 퍼블리싱합니다.,

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
닉네임, 비번 변경, 회원 탈퇴는 회원가입 pr 머지 되면 공통 컴포넌트로 작업하겠습니다!

## Questions

- 💬 질문 사항이에요!
   - 토글 스위치 애니메이션으로 구현했는데 맞을까요???
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-05-07 14:12 UTC, tlshoon commented
탭 추가하여 다시 올렸습니다!

2023-05-19 18:16 UTC, minsoo-web requested changes
리뷰 남깁니다 재훈님!

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/configItem.ts
config.constants.ts 가 조금 더 직관적인 것 같습니다

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/configItem.ts
> +  href?: T;
제네릭으로 선언할 필요가 있나요? 옵셔널로 선언하면 될 것 같아서요

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/myPage.styles.ts
> +  `;
여기서 따로 선언하신 이유가 있나요? 이미 만든 게 있어서요

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/myPage.styles.ts
> +  position: fixed;
fixed 를 쓰신 이유가 있으신가요??

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/notification/index.page.tsx
> +];
상수는 파일로 따로 관리하는 습관을 들입시다!

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/notification/notification.styles.ts
> +  position: fixed;
fixed를 써야하는 이유가 있나요..?!

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/notification/notification.styles.ts
> +  display: flex;
flex 함수가 있습니다!

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/notification/notification.styles.ts
> +  cursor: pointer;
pointer를 쓰지말고 태그를 button을 쓰는건 어떨까요?

2023-05-19 18:16 UTC, minsoo-web commented on src/pages/config/notification/toggleSwitch.tsx
> +}
타입은 따로 파일로 관리하는 습관을 들입시다!

2023-05-20 13:02 UTC, tlshoon commented on src/pages/config/notification/notification.styles.ts
> +  position: fixed;
fixed를 안 하면 화면 밖까지 스크롤하면 보이는데 상관 없을까요??

2023-05-20 13:24 UTC, tlshoon commented on src/pages/config/notification/notification.styles.ts
> +  cursor: pointer;
pointer 지우고 export const Switch = styled.button`으로 변경했습니다!

2023-05-26 07:19 UTC, minsoo-web approved these changes
충돌난 부분만 해결해주세요!

2023-05-28 09:52 UTC, merged