#30 회원가입 api 아이디 중복확인
UnivChat/web-client pull request #31
Opened 2023-06-19 11:41 UTC by tlshoon

# Describe your changes
아이디 중복확인 api추가

## Issue ticket number and link (optional)
#30 

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
- [x] 아이디 중복확인
- [ ] 이메일 인증 처리
- [ ] 입력한 이메일이 유효한지 검증하기
- [ ] 회원가입 API call

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
      - 이메일 인증 처리 작업 하겠습니다. 그런데 혹시 이메일 유효성 검증은 어떻게 하면 될까요!!??
- 🔥 이건 꼭 확인해주세요!

2023-06-23 02:11 UTC, minsoo-web requested changes
재훈님,
useMutation 을 활용해서 api 통신할 수 있도록 수정해주시고,
axios를 직접 호출하지말고, createAxiosInstance 함수를 통해서 작업해주세요 (state > server 폴더 참고)

2023-06-23 02:11 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +  const [email, setEmail] = useState<string>("");
명시하지 않아도 string 입니다. 불필요한 제네릭은 안 쓰는 게 낫습니다!

2023-06-23 02:11 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +    useState<string>("#003091");
마찬가지로 알아서 추론되는 타입 입니다.

2023-06-23 02:11 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +      if (response.data.code === "1000") {
여기서는 catch 에 걸리지 않으면 성공이기 때문에 불필요한 제어문입니다.
그리구 useMutaion의 onSuccess 로 처리해주세용

2023-06-23 02:11 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleEmailChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
ChangeEventHander 라고 있습니당

2023-07-02 08:08 UTC, tlshoon commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleEmailChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
넵 수정하겠습니다!

2023-07-07 13:10 UTC, tlshoon commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +    mutation.mutate(email);
이 부분에서  'string' 형식의 인수는 'void' 형식의 매개 변수에 할당될 수 없습니다. 이런 에러가 납니다. 어디서 void가 나오는지 말 모르겠습니다.. 코드 실행은 되는데 에러 해결이 안되는데 무슨 문제 일까요??

2023-07-07 17:13 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +    mutation.mutate(email);
리뷰 반영 작업 끝나시면 한 번 보겠습니다!

2023-07-08 01:49 UTC, tlshoon commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +    mutation.mutate(email);
넵 감사합니다!! 회원가입할 때 중복확인을 눌러도 라우팅되는 문제가 있어서 해결해서 올렸습니다!!

2023-07-09 12:53 UTC, minsoo-web requested changes
리뷰 드립니다! 미들웨어를 제가 공유를 안 드렸었네요 ㅠ 죄송합니다. 고생 많으셨어요!!

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/chagePw.type.ts
> +  handleConfirmPasswordChange: (e: ChangeEvent<HTMLInputElement>) => void;
EventHandler 타입을 사용하면 좀 더 편합니다 :)

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/chagePw.type.ts
파일명에 오타가 있네요 ! 

<img width="481" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/3bf128c8-c850-46dc-a714-b89d151c41af">

추천드립니다 !!

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const email = useSelector((state: RootState) => state.email);
```suggestion
  const email = useAppSelector(({email})=> email )
```

이렇게 하실 수 있습니다 :)

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const dispatch = useDispatch();
이것도 useAppDispatch 를 쓰는 게 조금 더 typed 하게 사용하실 수 있습니다. 

무슨 차이인가요?

-> useDispatch는 무슨 액션이든 액션이면 다 실행해줍니다. 
-> useAppDispatch는 정의된 리듀서 안에서 정의된 액션들만 실행시켜줍니다.

<img width="543" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/2ab0a979-537d-4886-81c2-16d12caba7f0">

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const [successMessage, setSuccessMessage] = useState("");
[react-hooks-form](https://www.react-hook-form.com/) 을 도입해보는 것을 추천드려요!! 정말 편합니다 :)

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +      }),
api 함수는 apis.ts에 따로 정의합니다 :)

지금 함수는 auth > apis.ts 에 정의해야겠네요

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const mutation = useMutation(
훅 또한 따로 정의하는 곳이 있습니다.
지금은 auth > hooks > auth.mutations.ts 에 정의하면 되겠네요 ㅎㅎ

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/sign-in/index.page.tsx
> +            type="text"
필요한 속성인가요? 🤔

2023-07-09 12:53 UTC, minsoo-web commented on src/pages/auth/sign-up/index.page.tsx
>            <CustomInput type="text" name="name" required {...name} />
type="text" 필요한 속성인가요?

2023-07-09 13:19 UTC, tlshoon commented on src/pages/auth/find-pw/changepw/chagePw.type.ts
> +  handleConfirmPasswordChange: (e: ChangeEvent<HTMLInputElement>) => void;
아!! EventHandler쓴다는 걸 계속 까먹네요! 감사합니다!

2023-07-09 13:21 UTC, tlshoon commented on src/pages/auth/find-pw/changepw/chagePw.type.ts
오오!! 이거 사용해야겠네요 감사합니다 파일명 수정하겠습니다 ㅎㅎ

2023-07-09 13:22 UTC, tlshoon commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const dispatch = useDispatch();
아 이런차이가 있었군요!!! 상세하게 설명해주셔서 감사합니다!

2023-07-25 07:05 UTC, tlshoon commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const [successMessage, setSuccessMessage] = useState("");
react-hooks-form사용해봤는데 state를 일일이 만들 필욕 정말 편하더라고요!! 그런데 react-hooks-form을 사용하면 상태를 그 컴포넌트 안에서만 관리를 할 수 있는 건가요?? 다른 컴포넌트에서 사용하려면 리덕스 스토어에 저장해서 사용해야할까요?

2023-07-26 03:18 UTC, tlshoon commented
api, mutation 파일 분리했습니다! 분리하면서 state를 사용할 수 없어서 엣지케이스 리덕스 스토어에 저장했습니다!

해결 해야하는 것
1.비번 성공적으로 변경후 다시 비번찾기 들어가면 인증 완료된 상태로 나옴
2.비번 성공적으로 변경시 성공 메세지 안뜸

2023-07-26 12:15 UTC, minjun232 commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +        if (data.code === "1000") {
여기서 사용되는 1000은 정해진 값인가요?? 아니면 임의로 설정하는 값인가요?

2023-07-26 12:15 UTC, minjun232 commented on src/pages/auth/find-pw/changepw/chagePw.type.ts
좋은 정보 감사합니다!

2023-07-26 12:27 UTC, tlshoon commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +        if (data.code === "1000") {
스웨거 보시면 통신에 성공하면 서버에서 반환해주는 값이 있습니다! 그 값입니다!

2023-07-26 17:10 UTC, minsoo-web commented on src/pages/auth/find-pw/changepw/changePw.hook.ts
> +  const [successMessage, setSuccessMessage] = useState("");
https://www.react-hook-form.com/api/useformcontext/ context API 를 지원합니다!

2023-07-26 17:19 UTC, minsoo-web requested changes
고생하셨어요! 조금만 더 수정해봅시다!

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.hooks.ts
> +  } = useSelector((state: RootState) => state.emailAuth);
useAppSelector ! 쓰시면 타입 선언 안 해도 됩니다

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleEmailChange: (e: ChangeEvent<HTMLInputElement>) => void;
Handler 써보시는 걸 추천드립니다~!

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleStartButtonClick: () => void;
voidFunction 쓰시는 방법이 또 있답니당

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/email-auth/index.page.tsx
>    } = useEmailAuth();
저는 이렇게 구조분해 할당이 길어지면
const hook = useEmailAuth();

이렇게 받아오고 꺼내서 씁니다.
hook.email 이런 식으루

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/find-pw/findPw.hooks.ts
> +  const email = useSelector((state: RootState) => state.email);
useAppSelector 를 쓰면 타입 선언을 안 해두 됩니다~!

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/find-pw/findPw.hooks.ts
> +    if (!email || !/^\S+@\S+\.\S+$/.test(email)) {
정규식은 따로 상수로 관리하는 게 좋습니다! constants 폴더에 따로 선언해서 관리해보세요~!

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/find-pw/findPw.hooks.ts
> +      }, 2000);
필요한 setTimeout 인가요?

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/sign-up/signUp.hooks.ts
> +  );
mutation과 api는 따로 파일로 분리해주세요.. ㅎㅎ

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/sign-up/signUp.hooks.ts
> +    }
훅과 api는 따로 파일로 분리해주세요 ㅎㅎ ㅠㅠ

2023-07-26 17:19 UTC, minsoo-web commented on src/pages/auth/sign-up/signUp.hooks.ts
> +    const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
아까 말씀 드린 정규식을 상수로 관리했을 때의 장점이 여기서 나오는거죠! 가져다 쓰면 되는겁니다

2023-07-27 01:47 UTC, tlshoon commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleEmailChange: (e: ChangeEvent<HTMLInputElement>) => void;
ChangeEventHandler를 사용하면 훅파일에서 'ChangeEventHandler<HTMLInputElement>' 형식에 'target' 속성이 없습니다.라는 에러가떠서 ChangeEvent를 쓸 때만 에러가 안나는데 해결 방법이 있을까요??!

2023-07-27 01:55 UTC, tlshoon commented on src/pages/auth/email-auth/index.page.tsx
>    } = useEmailAuth();
헉! 훨씬 깔끔하고 좋습니다!! 감사합니다!!!ㅎㅎ

2023-07-27 15:49 UTC, tlshoon commented on src/pages/auth/find-pw/findPw.hooks.ts
> +      }, 2000);
setTimeout을하지 않고 실행을하면 
https://github.com/UnivChat/web-client/assets/87574833/d76b8efb-e3e4-4a5b-94f6-b0288c8d3cef
이렇게 인증 성공 메세지가 뜨지 않고 화면이 기존 화면이 바뀌었다가 라우팅 되는 문제가 있습니다. 그래서 시간을 두고 dispatch해주면
https://github.com/UnivChat/web-client/assets/87574833/10ad0b9e-7399-41e3-a7b1-fe6a4ab43f5e
인증 성공 메세지와 함께 자연스럽게 라우팅이 되어서 setTimeOut함수를 썼습니다!! 혹시 좋은 방법 있을까요!?

2023-07-30 13:11 UTC, minsoo-web commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleEmailChange: (e: ChangeEvent<HTMLInputElement>) => void;
<img width="1319" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/631ce677-d875-4e38-9ced-dfc2335d8b85">

흠,, 저는 에러가 발생하지 않는데, react 에서 가져온 `ChangeEventHandler` 을 사용하셨을까요?

2023-07-30 13:23 UTC, minsoo-web commented on src/pages/auth/find-pw/findPw.hooks.ts
> +      }, 2000);
<img width="725" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/8b03be23-1843-4863-aad5-f7f54eb566db">

일단, 기존 화면이 바뀌었다가 라우팅 되는 문제라기보다는, 
routing이 끝나기 전에 화면이 리렌더링되기 때문에 생기는 문제라고 보시면 되구, 리렌더링이 되는 이유는 dispatch를 통해서 화면이 다시 그려지기 때문인 상황이라고 보시는 게 맞을 것 같습니다.

근본적인 해결방법은
성공했을 때 dispatch를 하는 이유가 초기화를 하기 위함이자나요?

useEffect의 return 콜백을 활용해서 언마운트 되었을 때 실행되는 코드들을 넣어주면 불필요하게 1~2초 기다리는 상황이 없어도 될 것 같습니다.

2023-07-30 13:25 UTC, minsoo-web commented on src/pages/auth/sign-up/signUp.hooks.ts
> +    const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
너무 잘 해주셨는데, regex는 하나만 존재하지 않는 경우가 많아서 파일당 하나의 정규식을 넣기보다는
regex.ts 같은 파일을 만들고 거기에 여러 정규식을 객체로 정의하는 게 편리합니다!

```js
const regex = {
  email: // here,
  id: // here,
  pw: // 
}
```

위처럼요!

2023-07-30 13:26 UTC, minsoo-web commented
추가 리뷰 남겨드렸습니다! 확인 부탁드릴게요~!

2023-07-30 14:28 UTC, tlshoon commented on src/pages/auth/find-pw/findPw.hooks.ts
> +      }, 2000);
헉.. 진짜 해결 되었네요.. 진짜 매번 느끼지만 대단함을 느낍니다.. useEffect 내에서 return하는 함수가 해당 컴포넌트가 언마운트 되는 시점에 호출되는군요 몰랐습니다! 또 배웁니다 감사합니다!

2023-07-30 14:34 UTC, tlshoon commented on src/state/server/auth/hooks/auth.mutations.ts
>        setTimeout(() => {
이 부분은 너무 성공 메세지가 너무 잠깐 보이고 라우팅 되어버려서 추가했습니다!

2023-07-30 14:35 UTC, tlshoon commented on src/state/server/auth/hooks/auth.mutations.ts
>          dispatch(clearEmail());
이 부분은 성공메세지가 너무 잠깐 보이고 라우팅이 되어버려서 추가했습니다.

2023-07-30 14:39 UTC, tlshoon commented on src/pages/auth/email-auth/emailAuth.type.ts
> +  handleEmailChange: (e: ChangeEvent<HTMLInputElement>) => void;
아! const handleEmailChange: ChangeEventHandler<HTMLInputElement> = (e) => {
  dispatch(setEmail(e.target.value));
};이렇게 사용해야하는데 제가   const handleEmailChange = (e: ChangeEventHandler<HTMLInputElement>) => {
    dispatch(setEmail(e.target.value));
  };이렇게 사용해서 에러가 났었네요.. 수정했습니다!! ㅎㅎ

2023-07-30 17:25 UTC, minsoo-web requested changes
리뷰 드립니다~!

2023-07-30 17:25 UTC, minsoo-web commented on src/pages/auth/sign-up/index.page.tsx
> +          <Styled.CheckIdButton onClick={e => handleIdCheck(e)}>
```suggestion
          <Styled.CheckIdButton onClick={handleIdCheck}>
```

이렇게 하셔도 됩니다 ㅎㅎ 불필요한 익명함수를 선언하지 않는 습관이 좋아요!

2023-07-30 17:25 UTC, minsoo-web commented on src/state/server/auth/hooks/auth.mutations.ts
> +import * as EmailAuthSlice from "@client-state/Auth/emailAuth/emailAuthSlice";
필요한 애들만 뽑아쓰면 될 것 같은데, *로 import 하는 이유가 있을까요?

2023-07-30 17:25 UTC, minsoo-web commented on src/state/client/Auth/signUp/signUpSlice.ts
> +    },
이런애들 하는 역할이 다 너무 똑같은데, 하나의 메소드로 퉁칠 수는 없을까요?
불필요하게 reducer가 많이 선언 되는 것 같아서요.

```
setSignUpInfo({key: 'password', value: '1234'});
setSignUpInfo({key: 'name', value: 'minsoo'});
```
사용하는 쪽에서는 이렇게 호출하고 선언하는 곳에서는 

```ts
  setConfirmPassword: (state, action: PayloadAction<any>) => {
      state[payload.key] = action.payload.value;
    },
```

any 타입을 쓰지 않는 방법으로는

```
setSignUpInfo: (
      state,
      {
        payload
      }: PayloadAction<{
        key: keyof SignUpBase;
        value: string;
      }>
    ) => {
      state[payload.key] = payload.value;
    },
```

<img width="442" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/345cdc56-b2ac-42d5-9093-3286b3f25644">


이렇게 하시면 됩니다

2023-07-31 07:23 UTC, tlshoon commented on src/state/server/auth/hooks/auth.mutations.ts
> +import * as EmailAuthSlice from "@client-state/Auth/emailAuth/emailAuthSlice";
변수명 들이 길어서 import문이 길어져서 저렇게 했는데 필요한 것만 뽑아쓰는 게 나을까요??

2023-08-01 01:47 UTC, tlshoon commented on src/state/client/Auth/signUp/signUpSlice.ts
> +    },
와.. 이렇게도 쓰는군요.. 진짜 중복 코드 사라지니까 기분이 좋네요 ㅋㅋㅋㅋ감사합니다 민수님!!

2023-08-02 09:50 UTC, minsoo-web commented on src/state/server/auth/hooks/auth.mutations.ts
> +import * as EmailAuthSlice from "@client-state/Auth/emailAuth/emailAuthSlice";
지금은 export 하는 파일 자체가 용량이 크지 않고 거의 다 사용하기 때문에 상관은 없지만, 항상 저렇게 import 하는 건 안 좋은 습관입니다. index.ts 파일에서 export를 많이 하면 할 수록 런타임 오버헤드가 증가합니다.

2023-08-02 09:51 UTC, minsoo-web approved these changes
긴 리뷰 고생 많으셨습니다!!

2023-08-02 09:52 UTC, merged

2023-08-02 10:46 UTC, tlshoon commented on src/state/server/auth/hooks/auth.mutations.ts
> +import * as EmailAuthSlice from "@client-state/Auth/emailAuth/emailAuthSlice";
아 그렇군요!! 이번 pr 민수님덕에 정말 많이 배웠습니다!! 감사합니다 민수님