#15 메인화면
UnivChat/web-client pull request #32
Opened 2023-06-26 10:25 UTC by minjun232

# Describe your changes
#15

## Issue ticket number and link (optional)

## Checklist

- [ ] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [ ] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [ ] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
학사일정, 공지사항 내용 채워야합니다.

## Questions

- 💬 질문 사항이에요!
하단바를 넣으니 본문 내용이 가려지는데 따로 div등으로 빈공간 만들어주어야하나요?

- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-06-26 17:01 UTC, minsoo-web requested changes
리뷰 남깁니다~!

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/Home.stories.tsx
좋은습관이네요 민준님!! 너무 잘 하셨습니다 ㅎㅎ
페이지로 따로 들어가지 않고 스토리북으로만 개발해본 경험이 어떠셨는지.. 궁금합니다!!

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/Home.styles.ts
> +  font-size: ${pxToRem(20)};
재훈님께는 제가 따로 리뷰 남겼었는데 비슷한 친구들끼리 묶어서 개행을 넣어주면 가독성이 많이 상승합니다!!

참고 링크 드리겠습니다!
https://github.com/UnivChat/web-client/pull/22#discussion_r1194222333

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/Home.styles.ts
> +  width: auto;
width: 'auto' 는 필요한 코드인가요?

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/Home.styles.ts
> +  width: 0;
필요한 친구인가요?!

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/Home.styles.ts
> +  width: auto;
이것두 필요한가요?!

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/Home.styles.ts
> +  width: auto;
얘두 필요한가요?!

2023-06-26 17:01 UTC, minsoo-web commented on src/pages/home/index.page.tsx
Home.tsx에 적힌 내용을 전부 여기로 옮겨도 되지 않을까요? Home.tsx가 따로 있어야 할 필요가 있는지 궁금합니다!

2023-06-29 01:50 UTC, minjun232 commented on src/pages/home/Home.stories.tsx
이번 기회에 처음 써봐서 좋았습니다ㅎㅎ 페이지단위로 작업하는것도 괜찮지만 확실히 컴포넌트 하나씩 작업할때는 굉장히 편하게 작업할수 있을것같습니다!

2023-06-29 01:50 UTC, minjun232 commented on src/pages/home/Home.styles.ts
> +  font-size: ${pxToRem(20)};
감사합니다!

2023-06-29 01:50 UTC, minjun232 commented on src/pages/home/index.page.tsx
전부 이동하였습니다!

2023-07-06 15:11 UTC, minsoo-web commented on src/pages/home/index.page.tsx
아 그냥 제가 데이터 연결 잘 되는지 확인차 넣은거라 삭제하셔도 무방합니다 (아니 삭제될 예정입니다!)

2023-07-06 15:13 UTC, minsoo-web approved these changes
너무 잘 해주셨네요 민준님 !! 리뷰 반영 감사합니다 :)

2023-07-06 15:13 UTC, merged