공지사항 크롤링 및 컴포넌트 작업합니다. #37
UnivChat/web-client pull request #38
Opened 2023-08-02 14:54 UTC by tlshoon

# Describe your changes

## Issue ticket number and link (optional)
#37 
## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
       크롤링해서 컴포넌트에 뿌리는 작업 했는데, 한 번 캐싱되면 괜찮은데 처음 데이터 가져올 떄 로딩이 너무 긴데 이게 맞는지 궁금합니다..  클라이언트 단에서 해결 가능한지 궁금합니다!! 아니면 서버에 넘겨서 받아오는 방법도 있다고 하는 것 같은데 방식을 바꾸는 게 좋을까요??
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-08-03 01:26 UTC, tlshoon commented
처음 렌더링 될 때 일반,학사,장학,취업 데이터를 프리페치 해서 탭을 이동할 때마다 로딩이 걸리는 문제 해결했습니다.

2023-08-06 13:26 UTC, minsoo-web requested changes
라이브로 말씀 드린 사항 같이 적용 부탁드립니다!

2023-08-07 12:35 UTC, tlshoon commented
1. 명확하지 않은 스타일 이름들 수정
2. 공지사항 카테고리 배열로 변경

수정해서 다시 커밋했습니다!

2023-08-13 05:36 UTC, minsoo-web requested changes

2023-08-13 05:36 UTC, minsoo-web commented on src/components/Home/Notice/Notice.stories.tsx
> +
preview.js 에서 선언해주세요!

2023-08-13 05:36 UTC, minsoo-web commented on src/components/Home/Notice/Notice.tsx
> +  const categories: string[] = ["일반", "학사", "장학", "취·창업"];
알아서 추론되는 타입입니다.

2023-08-13 05:36 UTC, minsoo-web commented on src/components/Home/Notice/NoticeContent/NoticeContent.tsx
> +      <ul>
불필요한 wrapper 태그인 것 같습니다!

2023-08-13 06:52 UTC, minsoo-web approved these changes

2023-08-13 06:52 UTC, merged