연락망 api 연동
UnivChat/web-client pull request #42
Opened 2023-08-13 13:27 UTC by tlshoon

# Describe your changes

## Issue ticket number and link (optional)

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-08-15 08:25 UTC, minsoo-web requested changes
리뷰 남깁니다 재훈님!

2023-08-15 08:25 UTC, minsoo-web commented on src/pages/home/contact/Contact.styles.ts
> +  justify-content: space-between;
flex 함수 쓰는 건 어떨까요?!

2023-08-15 08:25 UTC, minsoo-web commented on src/pages/home/contact/Contact.styles.ts
> +  padding: ${pxToRem(13)} ${pxToRem(16)} ${pxToRem(13)} ${pxToRem(16)};
축약으로 적는 게 가독성 측면에서 더 나아보입니다!

2023-08-15 08:25 UTC, minsoo-web commented on src/pages/home/contact/index.page.tsx
> +  const [searchTerm, setSearchTerm] = useState("");
연락망인데 term이라고 명명하신 이유가 있으신가요?
<img width="482" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/ae024fae-c503-4ddf-a15b-c095123f15fb">

2023-08-15 08:25 UTC, minsoo-web commented on src/pages/home/contact/index.page.tsx
> +  const [activeIndex, setActiveIndex] = useState<number | null>(null);
<img width="354" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/2f286163-3bad-4926-9874-76d8069b8482">

현재 ui는 여러 개를 열 수 있는 ui입니다.
하나만 열리도록 변경하거나, 여러개가 열려도 arrow 방향이 똑같도록 처리해주세요

2023-08-15 08:25 UTC, minsoo-web commented on src/pages/home/contact/index.page.tsx
> +            {filteredContacts.map((contact: ContactDTO, index: number) => (
타입 선언을 지워도 잘 됩니다. map은 타입을 추론해서 가져오거든요

2023-08-15 08:25 UTC, minsoo-web commented on src/pages/home/contact/index.page.tsx
> +                  )}
```suggestion
<Styled.ArrowIcon
                    svgName={
                      activeIndex === index ? "belowarrow" : "rightarrow"
                    }
                  />
```

이렇게는 어떠신가요?

2023-08-15 08:25 UTC, minsoo-web commented on src/state/server/home/notice/api.ts
> +};
타입선언을 여기서부터 해서 가져오면 reactQuery가 추론된 타입으로 data를 가져옵니다. 

as를 사용하지 않고,
axios의 response의 타입을 어떻게 추론하는지 한 번 찾아보세요!

2023-08-15 08:25 UTC, minsoo-web commented on src/state/server/home/notice/hooks/contact.queires.ts
> +  return useQuery<ContactDTO[]>(["contact"], fetchContact);
키는 중복되면 안 되기 때문에 하나의 파일에서 변수로 관리하는 게 좋습니다. 
auth/keys.ts 파일을 참조해주세요

2023-08-15 10:13 UTC, tlshoon commented on src/pages/home/contact/index.page.tsx
> +                  )}
오오 깔끔하고 좋습니다!

2023-08-15 17:55 UTC, minsoo-web commented
아 그리구 충돌난 부분도 해결해주세요!!
![image](https://github.com/UnivChat/web-client/assets/57122180/f299e278-f087-434c-a771-a2033e579f68)

2023-08-16 08:46 UTC, minsoo-web requested changes
리뷰 한 번 더 드립니다!

2023-08-16 08:46 UTC, minsoo-web commented on src/pages/home/contact/index.page.tsx
> +  const [searchContact, setSearchContact] = useState("");
상관은 없는 리뷰인데, contactSearchInput 이 조금 더 가독성 있는 변수명인 것 같아요!

2023-08-16 08:46 UTC, minsoo-web commented on src/pages/home/contact/index.page.tsx
> +export default Contact;
안 쓰이는 거 지웁시다!

2023-08-16 08:46 UTC, minsoo-web commented on src/state/server/home/api.ts
> +};
이렇게 명명하면 어떤 api에 쓰이는 response인지 알아볼 수가 없죠..?!

그리고 제가 만들어둔 제네릭 response 가 있어서 그거 가져다 쓰시면 됩니다

<img width="433" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/13c388cb-731d-49d6-9b27-e64a2e3aa5c8">

2023-08-16 08:46 UTC, minsoo-web commented on src/state/server/home/api.ts
> +  const res = await api.get<ApiResponse>("/school/phone");
```suggestion
  const res = await api.get<API.DefaultResponse<Contact[]>>("/school/phone");
```

일케 하시면 됩니다

2023-08-16 08:46 UTC, minsoo-web commented on src/state/server/queryKey.ts
> +  contact = "CONTACT"
이건 좀 애매한 리뷰이긴한데, 여기에 명시하는 건 도메인이에요.

그래서 home을 여기다가 명시하고, home/keys.ts 에서 contact 관련된 걸 명시하면 됩니다.

2023-09-08 17:45 UTC, minsoo-web approved these changes

2023-09-08 17:46 UTC, merged