#33 문의하기 페이지 리팩터링
UnivChat/web-client pull request #44
Opened 2023-08-15 08:22 UTC by Duck-98

# Describe your changes
1. 문의하기 페이지 스타일링을 수정했습니다.
2. react-hook-form 적용
3. 버튼 disabled 적용
4. Header 배경색 custom할 수 있게 변경

<img width="360" alt="스크린샷 2023-08-15 오후 5 10 36" src="https://github.com/UnivChat/web-client/assets/72850354/5316474e-1534-43fb-8226-779288e47907">

### 초기화면과 이메일 형식에 맞지 않게 썼거나, 체크박스를 체크하지않았거나 문의 내용을 입력하지 않았을 때
### 문의 접수하기가 disabled 되서 클릭할 수 없고 색이 변합니다.

<img width="359" alt="스크린샷 2023-08-15 오후 5 11 04" src="https://github.com/UnivChat/web-client/assets/72850354/3290f4ad-926d-4d56-a37a-dc82033e01d6">

### 형식에 맞게 입력하게 되면 버튼이 활성화 됩니다.

### 추가적으로 Header의 배경색이 사용되는 위치마다 달라서 배경색을 props로 전달할 수 있게 바꿨습니다.

```tsx
// 기존 코드
export const Header = ({ title, subTitle, element }: HeaderProps) => {
  return (
    <>
      <Styled.Header>
        {element?.left}
        <Styled.Title>{title}</Styled.Title>
        <Styled.SubTitle>{subTitle}</Styled.SubTitle>

        <div style={{ flex: 1 }} />
        {element?.right}
      </Styled.Header>
      <Styled.MarginContainer />
    </>
  );
};
<Header.Back title="문의하기" />

```

```tsx
// 변경된 코드 
export const Header = ({ title, subTitle, element, bgColor }: HeaderProps) => {
  return (
    <>
      <Styled.Header bgColor={bgColor}>
        {element?.left}
        <Styled.Title>{title}</Styled.Title>
        <Styled.SubTitle>{subTitle}</Styled.SubTitle>

        <div style={{ flex: 1 }} />
        {element?.right}
      </Styled.Header>
      <Styled.MarginContainer />
    </>
  );
};

<Header.Back bgColor={colors.white} title="문의하기" />

```

## Issue ticket number and link (optional)

## Checklist

- [x] 🤔 이 프로젝트의 스타일 가이드를 따르나요?
- [x] 🤔 머지하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?
- [x] ⛔️ (필수) base 브랜치를 pull 받았나요?!

## Next Step Todo (optional)
문의하기 API 연동 및 type 수정

## Questions

- 💬 질문 사항이에요!
- 🤷‍♂️ 확인 받고 싶은 부분이에요!
- 🔥 이건 꼭 확인해주세요!

2023-08-15 08:36 UTC, minsoo-web requested changes
<img width="322" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/28d4e28d-0eec-4a91-892f-0594190aede4">

<img width="93" alt="image" src="https://github.com/UnivChat/web-client/assets/57122180/74435cce-d382-49c0-934d-1fbbbcb693a3">


padding을 추가해주세요!

이메일은 입력된 버전이 없긴한데, textarea 랑 통일해주세요

2023-08-15 08:36 UTC, minsoo-web commented on src/components/Common/UI/Header/Header.styles.ts
> +  background: ${({ bgColor }) => bgColor || colors.grayf8};
```suggestion
  background: ${({ bgColor =  colors.grayf8 }) => bgColor};
```

요건 어떠신가요? 불필요한 제어문이 없어집니다

2023-08-15 08:36 UTC, minsoo-web commented on src/pages/config/inquiry/Inquiry.styles.ts
> +  column-gap: ${pxToRem(11)};
그냥 gap으로만 쓰셔도 될 것 같은데, 따로 이유가 있으신가요?

2023-08-15 08:36 UTC, minsoo-web commented on src/pages/config/inquiry/Inquiry.styles.ts
> +  /* border: 1px solid #d0d3d5; */
불필요한 주석은 지웁시다!

2023-08-15 08:36 UTC, minsoo-web commented on src/pages/config/inquiry/Inquiry.styles.ts
> +  border: 1px solid red;
안 쓰이는 코드 같은데, 지웁시다!

2023-08-15 08:36 UTC, minsoo-web commented on src/pages/config/inquiry/Inquiry.styles.ts
>    font-weight: 600;
없어져야 하는 값인 것 같습니다

2023-08-15 08:37 UTC, Duck-98 commented on src/components/Common/UI/Header/Header.styles.ts
> +  background: ${({ bgColor }) => bgColor || colors.grayf8};
엇 이렇게 바꾸겠습니다

2023-08-15 08:38 UTC, Duck-98 commented on src/pages/config/inquiry/Inquiry.styles.ts
> +  column-gap: ${pxToRem(11)};
gap으로 바꾸겠습니다!

2023-09-08 17:46 UTC, minsoo-web approved these changes

2023-09-08 17:46 UTC, merged